# Generated by Django 5.0.2 on 2024-03-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_categoria_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
