# Generated by Django 5.0.2 on 2024-03-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_categoria_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField()),
                ('custo', models.FloatField(default=0.0)),
                ('preco', models.FloatField(default=0.0)),
                ('check_in_data', models.DateTimeField()),
                ('check_out_data', models.DateTimeField()),
                ('vagas_disponiveis', models.IntegerField(default=0)),
                ('cover', models.ImageField(default='', upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.categoria')),
            ],
        ),
    ]
