# Generated by Django 5.0.2 on 2024-03-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
