# Generated by Django 5.0.2 on 2024-03-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_alter_viagem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
