# Generated by Django 5.0.2 on 2024-03-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_alter_viagem_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='vagas_disponiveis',
            field=models.IntegerField(),
        ),
    ]
