# Generated by Django 5.0.2 on 2024-03-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_alter_viagem_vagas_disponiveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='vagas_disponiveis',
            field=models.IntegerField(),
        ),
    ]
