# Generated by Django 5.0.2 on 2024-03-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_alter_viagem_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='cover',
        ),
    ]
