# Generated by Django 5.0.2 on 2024-03-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_remove_viagem_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='custo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
