# Generated by Django 5.0.2 on 2024-03-14 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_alter_viagem_cover'),
        ('user', '0002_cliente_created_at_cliente_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViagensCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cliente')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.viagem')),
            ],
        ),
    ]
